language: rust
rust:
  - 1.20.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
      env: FEATURES="--features nightly"
script:
  - cargo test $FEATURES
  - cargo test --no-default-features $FEATURES
