language: rust
matrix:
  include:
    - rust: 1.20.0
    - rust: stable
    - rust: stable
      os: osx
    - rust: beta
    - rust: nightly
      script:
        - cargo test
        - cargo test --features nightly
        - cargo test --no-default-features
        - cargo test --no-default-features --features nightly
script:
  - cargo test
  - cargo test --no-default-features
  - cargo test --manifest-path derive/Cargo.toml
  - cargo test --manifest-path derive/Cargo.toml --no-default-features
