[package]
name = "unchecked_convert_derive"
version = "0.1.0"
authors = ["Nikolai Vazquez"]
license = "MIT/Apache-2.0"
repository = "https://github.com/nvzqz/unchecked-convert-rs"
categories = ["no-std"]
description = "Derive functionality for unchecked conversion traits."

[lib]
proc-macro = true

[badges]
travis-ci = { repository = "nvzqz/unchecked-convert-rs" }

[features]
default = ["std"]
std = []

[dependencies]
syn = "0.11"
quote = "0.3"
regex = "0.2"
